/**
 * NOTE: This class is auto generated by the swagger code generator program (2.2.3).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.model.InlineResponse200;

import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import java.util.List;
import javax.validation.constraints.*;
import javax.validation.Valid;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2017-08-24T16:07:52.906Z")

@Api(value = "locations", description = "the locations API")
public interface LocationsApi {

    @ApiOperation(value = "", notes = "Retrieve ATM or Branch locations for the bank.", response = InlineResponse200.class, responseContainer = "List", tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Success", response = InlineResponse200.class, responseContainer = "List") })
    
    @RequestMapping(value = "/locations",
        method = RequestMethod.GET)
    ResponseEntity<List<InlineResponse200>> getLocations( @NotNull@ApiParam(value = "Search radius in Miles", required = true) @RequestParam(value = "radius", required = true) String radius, @NotNull@ApiParam(value = "", required = true) @RequestParam(value = "maxResults", required = true) String maxResults, @NotNull@ApiParam(value = "", required = true) @RequestParam(value = "state", required = true) String state, @NotNull@ApiParam(value = "", required = true) @RequestParam(value = "zipCode", required = true) String zipCode, @NotNull@ApiParam(value = "Possible values \"ATM\" or \"Branch\"", required = true) @RequestParam(value = "locationType", required = true) String locationType,@ApiParam(value = "") @RequestParam(value = "streetName", required = false) String streetName,@ApiParam(value = "") @RequestParam(value = "city", required = false) String city,@ApiParam(value = "") @RequestParam(value = "streetNumber", required = false) String streetNumber,@ApiParam(value = "") @RequestParam(value = "crossStreet", required = false) String crossStreet,@ApiParam(value = "") @RequestParam(value = "longitude", required = false) String longitude,@ApiParam(value = "") @RequestParam(value = "latitude", required = false) String latitude);

}
